logback:
  appname: snail-eureka
  logdir: /usr/app/deploy/snail-eureka/logs


#单机  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:18080/eureka/ #注册中心地址
    register-with-eureka: false #表明该实例是否应该与尤里卡服务器登记其信息被别人发现。在某些情况下,您不希望您的实例被发现而你想发现其他实例。默认为true
    fetch-registry: false #表明这个客户是否应该从尤里卡服务器获取尤里卡注册表信息。默认为true  


#集群
server:
  port: 18080
spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: 123456 
   #用户名与密码若是不配置，系统会自动生成并打印在控制台日志上
   
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: true
#  server:
#    enable-self-preservation: true
#    peer-node-read-timeout-ms: 5000
#    
#    
#management:
#  endpoints:
#    web:
#      base-path: /
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always
#    restart:
#      enabled: true
#  server:
#    port: 18080
#---
#spring:
#  profiles: eureka-jy
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka-B:18080/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@eureka-C:18080/eureka/
#  instance:
#    hostname: eureka-A
#---
#spring:
#  profiles: eureka-lhn
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka-A:18080/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@eureka-C:18080/eureka/  
#  instance:
#    hostname: eureka-B
#---
#spring:
#  profiles: eureka-zsm
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka-A:18080/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@eureka-B:18080/eureka/
#  instance:
#    hostname: eureka-C



      
# https://www.cnblogs.com/li3807/p/7282492.html      
# https://www.jb51.net/article/156272.htm  配置讲解地址      
# https://www.cnblogs.com/bqzz/p/10294326.html 配置讲解地址