logback:
  appname: snail-eureka
  logdir: /usr/app/deploy/snail-eureka/logs

server:
  port: 18080

eureka:
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 5000
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

spring:
  security:
    user:
      name: admin
      password: 123456
      
      
# https://www.jb51.net/article/156272.htm  配置讲解地址      
