snail:
  spring:
    data:
      jdbc:
        druid-d-b-cfg:
          driverClassName: com.mysql.jdbc.Driver
          url: jdbc:mysql://116.62.20.123:3306/demo?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
          username: root
          password: "858409517"
          initialSize: 1 # 启动时初始化的创建的连接个数
          maxActive: 50 #可以在池中保持空闲的最大连接数，超出设置值之外的空闲连接将被回收，如设置为-1不限制
          minIdle: 5 #可以在池中保持空闲的最小连接数，超出设置值之外的空闲连接将被创建，如设置为0不创建
          maxWait: 10000 # 如果没有可用连接,在抛出异常前等待的一个连接被归还的最大毫秒数，设置为-1， 设为-1无限制
          removeAbandonedTimeout: 180 # 已抛弃的连接可以被移除的超时时间，单位为秒
          removeAbandoned: true #超过removeAbandonedTimeout时间后，进行已抛弃的回收
          timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          minEvictableIdleTimeMillis: 300000  #配置一个连接在池中最小生存的时间，单位是毫秒
          validationQuery: SELECT 1 FROM DUAL  #用来检测连接是否有效的sql，要求是一个查询语句
          testWhileIdle: false  #申请连接的时候检测
          testOnBorrow: false #申请连接时执行validationQuery检测连接是否有效，配置为true会降低性能
          testOnReturn: false #归还连接时执行validationQuery检测连接是否有效，配置为true会降低性能
          poolPreparedStatements: true #打开PSCache，并且指定每个连接上PSCache的大小
          maxOpenPreparedStatements: 50 #打开PSCache，并且指定每个连接上PSCache的大小
          filters: stat # 属性类型是字符串，常用插件有:监控统计filter:stat、 日志filter:log4j、 防御SQL注入filter:wall
        config-location: classpath:config/SqlMapConfig.xml
        mapper-locations: classpath*:mapper/*.xml
      redis:
        redisPoolCfg:
            minIdle: 1 #可以在池中保持空闲的最小连接数
            maxIdle: 10 #可以在池中保持空闲的最大连接数
            maxTotal: 50 #最大连接数
            maxWaitMillis: 60000 # 如果没有可用连接,在抛出异常前等待的一个连接被归还的最大毫秒数，设置为-1， 设为-1无限制
            testWhileIdle: false # 申请连接的时候检测
            testOnCreate: false
            testOnBorrow: false # 申请连接时执行validationQuery检测连接是否有效，配置为true会降低性能
            testOnReturn: false # 归还连接时执行validationQuery检测连接是否有效，配置为true会降低性能
        redisShardCfg:
            connectionTimeout: 60000
            soTimeout: 60000
            password: "123456"
        hostsCfg:
            - redis://116.62.20.123:6379
        dbIndex: 1   
  rabbit:
    host: 116.62.20.123
    virtual-host: testone
    username: testone
    password: testone
    port: 5672  
#  rabbit:
#    host: localhost
#    virtual-host: testone
#    username: guest
#    password: guest
#    port: 5672
  swagger:
    enable: true #生产环境需要关闭接口文档 设置成false
    service-url: "http://localhost:34000/snail-demo/" # 服务接口路径
    description: "蜗牛工作空间demo系统"
    title: "蜗牛工作空间demo系统"
    version: "1.0"
    swagger-url: "http://localhost:34000/snail-demo/doc.html"
    swagger-header-params:
     - name: app_id
       description: "应用ID"
       required: false
     - name: order_no
       description: "流水号"
       required: false
     - name: version
       description: "版本号"
       required: false
     - name: global_token
       description: "全局token"
       required: false
     - name: timestamp
       description: "操作时间"
       required: false       

eureka:
  client:
    serviceUrl:
      defaultZone: "http://192.168.17.11:18080/eureka"
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${server.port}
#    ip-address: 127.0.0.1

feign:
  httpclient:
    enabled: true

ribbon:
  ReadTimeout: 30000 #请求处理的超时时间
  ConnectTimeout: 15000 #请求连接的超时时间
